# Generated by Django 3.0.8 on 2020-07-26 20:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conviction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1000, verbose_name='name')),
                ('Position', models.IntegerField()),
            ],
            options={
                'verbose_name': 'conviction',
                'verbose_name_plural': 'convictions',
            },
        ),
        migrations.CreateModel(
            name='Diagnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1000, verbose_name='name')),
                ('Description', models.CharField(max_length=50000, verbose_name='description')),
            ],
            options={
                'verbose_name': 'diagnos',
                'verbose_name_plural': 'diagnoses',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1000, verbose_name='name')),
                ('StartDiagnosis', models.DateField(default='1999-01-01', null=True)),
                ('Note', models.CharField(max_length=50000, verbose_name='note')),
            ],
            options={
                'verbose_name': 'diagnosis',
                'verbose_name_plural': 'diagnostics',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=200, verbose_name='login')),
                ('email', models.CharField(max_length=200, verbose_name='email')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
                ('FIO', models.CharField(default='', max_length=50, verbose_name='last first middle name')),
                ('SocialNetwork', models.CharField(default='', max_length=50, verbose_name='SocialNetwork')),
                ('Position', models.CharField(default=' ', max_length=50, verbose_name='position')),
                ('Department', models.CharField(default='', max_length=50, verbose_name='department')),
            ],
            options={
                'verbose_name': 'doctor',
                'verbose_name_plural': 'doctors',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1000, verbose_name='name')),
                ('DateForm', models.DateField(default='1999-01-01', null=True)),
                ('Note', models.CharField(max_length=50000, verbose_name='note')),
                ('Conviction', models.IntegerField()),
                ('Diagnos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Diagnos')),
                ('Diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Diagnosis')),
            ],
            options={
                'verbose_name': 'form',
                'verbose_name_plural': 'forms',
            },
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1000, verbose_name='name')),
                ('Coef', models.FloatField()),
            ],
            options={
                'verbose_name': 'frequency',
                'verbose_name_plural': 'frequency',
            },
        ),
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumberRecord', models.CharField(max_length=200, verbose_name='number record')),
                ('FIO', models.CharField(max_length=200, verbose_name='FIO')),
                ('Birthday', models.DateField(default='1999-01-01', null=True)),
                ('Sex', models.CharField(max_length=200, verbose_name='sex')),
                ('Adress', models.CharField(max_length=200, verbose_name='adress')),
                ('Phone', models.CharField(max_length=50, verbose_name='phone')),
            ],
            options={
                'verbose_name': 'patient',
                'verbose_name_plural': 'patients',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Diagnos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Diagnos')),
                ('Frequency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Frequency')),
            ],
            options={
                'verbose_name': 'rule',
                'verbose_name_plural': 'rules',
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1000, verbose_name='name')),
                ('Description', models.CharField(max_length=50000, verbose_name='description')),
            ],
            options={
                'verbose_name': 'symptom',
                'verbose_name_plural': 'symptoms',
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, verbose_name='name')),
                ('Date', models.DateField(default=datetime.date(2020, 7, 27))),
                ('Note', models.CharField(max_length=5000, verbose_name='note')),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Doctor')),
                ('Record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PatientRecord')),
            ],
            options={
                'verbose_name': 'treatment',
                'verbose_name_plural': 'treatments',
            },
        ),
        migrations.CreateModel(
            name='SelectedSymptomsDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Note', models.CharField(max_length=50000, verbose_name='note')),
                ('Conviction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Conviction')),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Doctor')),
                ('Symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Symptom')),
            ],
            options={
                'verbose_name': 'selected doc symptom',
                'verbose_name_plural': 'selected doc symptoms',
            },
        ),
        migrations.CreateModel(
            name='SelectedSymptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Note', models.CharField(max_length=50000, verbose_name='note')),
                ('Conviction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Conviction')),
                ('Form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Form')),
                ('Symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Symptom')),
            ],
            options={
                'verbose_name': 'selected symptom',
                'verbose_name_plural': 'selected symptoms',
            },
        ),
        migrations.CreateModel(
            name='RuleSymptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Conviction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Conviction')),
                ('Rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Rule')),
                ('Symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Symptom')),
            ],
            options={
                'verbose_name': 'rule symptom',
                'verbose_name_plural': 'rules symptom',
            },
        ),
        migrations.CreateModel(
            name='PatientList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Doctor')),
                ('PatientRecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PatientRecord')),
            ],
        ),
        migrations.CreateModel(
            name='Epicrisis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Referral', models.CharField(max_length=1000, verbose_name='referral')),
                ('Therapy', models.CharField(max_length=50000, verbose_name='therapy')),
                ('Disability', models.CharField(max_length=1000, verbose_name='disability')),
                ('Hospitalization', models.DateField(default='1999-01-01', null=True)),
                ('HospitalDischarge', models.DateField(default='1999-01-01', null=True)),
                ('IsOver', models.IntegerField()),
                ('Treatment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Treatment')),
            ],
            options={
                'verbose_name': 'epicrisis',
                'verbose_name_plural': 'epicrises',
            },
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='Doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Doctor'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='Treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Treatment'),
        ),
        migrations.CreateModel(
            name='Anamesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Diagnos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Diagnos')),
                ('Treatment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Treatment')),
            ],
            options={
                'verbose_name': 'Anamesis',
                'verbose_name_plural': 'Anamesises',
            },
        ),
    ]
