# Generated by Django 3.0.8 on 2020-07-23 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frequency',
            options={'verbose_name': 'frequency', 'verbose_name_plural': 'frequency'},
        ),
        migrations.AlterField(
            model_name='rulesymptom',
            name='Rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Rule'),
        ),
    ]
