# Generated by Django 3.0.8 on 2020-07-23 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200723_0523'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedSymptomsDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Note', models.CharField(max_length=50000, verbose_name='note')),
                ('Conviction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Conviction')),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Doctor')),
                ('Symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Symptom')),
            ],
            options={
                'verbose_name': 'selected symptom',
                'verbose_name_plural': 'selected symptoms',
            },
        ),
    ]
